<?php include "includes/header.php";?>

<h2 class="pageID"><?=$pageID?></h2>
       <!-- <img class="desktop" src="images/placeholder800.jpg" alt="Placeholder image" />
       <img class="tablet" src="images/placeholder500.jpg" alt="Placeholder image" />
       <img class="phone" src="images/placeholder320.jpg" alt="Placeholder image" /> -->
       <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed vulputate mi sit amet mauris commodo quis imperdiet. Purus non enim praesent elementum facilisis. Amet cursus sit amet dictum. Dignissim diam quis enim lobortis. At imperdiet dui accumsan sit. Aenean sed adipiscing diam donec adipiscing. Volutpat ac tincidunt vitae semper quis lectus nulla. Sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae. Pellentesque habitant morbi tristique senectus et netus et malesuada. Enim eu turpis egestas pretium aenean pharetra magna ac placerat. Et netus et malesuada fames ac. Augue lacus viverra vitae congue eu. Morbi tempus iaculis urna id volutpat.</p>
       <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
       <p>Rhoncus dolor purus non enim. Ut eu sem integer vitae justo eget magna fermentum. Enim sit amet venenatis urna cursus eget nunc scelerisque. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque. Vel elit scelerisque mauris pellentesque pulvinar pellentesque. Eu turpis egestas pretium aenean pharetra. Etiam erat velit scelerisque in dictum non. Nulla posuere sollicitudin aliquam ultrices sagittis orci a. Fusce ut placerat orci nulla pellentesque dignissim enim sit. Maecenas ultricies mi eget mauris pharetra et. Consectetur purus ut faucibus pulvinar elementum. Tellus molestie nunc non blandit massa enim. Non nisi est sit amet facilisis magna etiam tempor. Consequat nisl vel pretium lectus quam id leo in vitae. Vulputate sapien nec sagittis aliquam malesuada. Vestibulum lectus mauris ultrices eros in cursus turpis massa. Porttitor lacus luctus accumsan tortor posuere ac ut consequat.</p>
       <p>Justo eget magna fermentum iaculis. Metus dictum at tempor commodo ullamcorper a lacus vestibulum. At volutpat diam ut venenatis tellus in metus. Elementum nisi quis eleifend quam adipiscing. Integer vitae justo eget magna fermentum. Sem integer vitae justo eget magna fermentum iaculis eu. Id neque aliquam vestibulum morbi blandit cursus risus at ultrices. Feugiat nibh sed pulvinar proin gravida hendrerit. Consectetur adipiscing elit duis tristique. Ac tincidunt vitae semper quis lectus nulla at volutpat diam. Eu mi bibendum neque egestas congue quisque. Vitae suscipit tellus mauris a. Vestibulum sed arcu non odio euismod lacinia at quis risus. Non curabitur gravida arcu ac tortor dignissim convallis. Orci sagittis eu volutpat odio facilisis mauris sit amet. Tortor posuere ac ut consequat semper viverra nam. Mus mauris vitae ultricies leo. Enim praesent elementum facilisis leo. At urna condimentum mattis pellentesque id nibh tortor id aliquet. Consectetur adipiscing elit ut aliquam purus sit.</p>
<?php include "includes/footer.php";?>